---
- name: create victoriametrics system group
  group:
    name: victoriametrics
    system: true
    state: present

- name: create victoriametrics system user
  user:
    name: victoriametrics
    system: true
    shell: "/usr/sbin/nologin"
    group: victoriametrics
    createhome: false
    home: "{{ victoriametrics_db_dir }}"

- name: create victoriametrics data directory
  file:
    path: "{{ victoriametrics_db_dir }}"
    state: directory
    owner: victoriametrics
    group: victoriametrics
    mode: 0755

- block:
    - name: download victoriametrics binary to local folder
      become: false
      get_url:
        url: "https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ victoriametrics_version }}/victoria-metrics-v{{ victoriametrics_version }}.tar.gz"
        dest: "/tmp/victoria-metrics-v{{ victoriametrics_version }}.tar.gz"
        checksum: "sha256:{{ __victoriametrics_checksum }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      # run_once: true # <-- this cannot be set due to multi-arch support
      delegate_to: localhost
      check_mode: false

    - name: unpack victoriametrics binaries
      become: false
      unarchive:
        src: "/tmp/victoria-metrics-v{{ victoriametrics_version }}.tar.gz"
        dest: "/tmp"
      delegate_to: localhost
      check_mode: false

    - name: propagate official victoriametrics binaries
      copy:
        src: "/tmp/{{ item }}"
        dest: "{{ victoriametrics_binary_install_dir }}/{{ item }}"
        mode: 0755
        owner: root
        group: root
      with_items:
        - victoria-metrics-prod
      notify:
        - restart victoria-metrics

  when:
    - not victoriametrics_skip_install

- name: create systemd service unit
  template:
    src: victoria-metrics.service.j2
    dest: /lib/systemd/system/victoria-metrics.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart victoria-metrics
