---
- block:
    - name: "Get checksum list"
      set_fact:
        __victoriametrics_checksums: "{{ lookup('url', 'https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v' + victoriametrics_version + '/victoria-metrics-v' + victoriametrics_version + '_checksums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum"
      set_fact:
        __victoriametrics_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __victoriametrics_checksums }}"
  delegate_to: localhost
  when:
    - not victoriametrics_skip_install
